# ============================================================================
# Dependabot Configuration - v2 (Fixed)
# ============================================================================
# Description: Automated dependency updates configuration
# Version: 2
# ============================================================================

version: 2
updates:
  # JavaScript/Node.js dependencies with Yarn 3
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5  # Reduced from 10
    reviewers:
      - "softengrahmed"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    # Versioning strategy for Yarn 3 compatibility
    versioning-strategy: "increase-if-necessary"
    # Group dependencies to reduce PR count
    groups:
      development:
        patterns:
          - "@nrwl/*"
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      production:
        patterns:
          - "express"
          - "react*"
          - "typeorm"
          - "pg"
        update-types:
          - "patch"  # Only patch updates for production deps
    # Ignore major updates to prevent breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Specific ignores for known issues
      - dependency-name: "typeorm"
        versions: ["0.4.x", "0.5.x"]  # Stay on 0.3.x
      - dependency-name: "@nrwl/*"
        versions: ["> 14.3.6"]  # Stay on current NX version

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3  # Reduced from 5
    reviewers:
      - "softengrahmed"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker - Fixed path
  - package-ecosystem: "docker"
    directory: "/docker/node"  # Specific path to Dockerfile
    schedule:
      interval: "monthly"  # Less frequent for Docker
      day: "monday"
    open-pull-requests-limit: 2
    reviewers:
      - "softengrahmed"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      # Keep Node.js 16.x for consistency
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]