nodeLinker: node-modules
npmRegistryServer: https://registry.yarnpkg.com

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-dlx.cjs

yarnPath: .yarn/releases/yarn-3.2.1.cjs

enableTelemetry: false
logFilters:
  - code: YN0013
    level: discard
