# Yarn 3 Configuration
yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules
enableGlobalCache: false

# Network settings for CI/CD
httpTimeout: 60000
networkConcurrency: 10

# Install settings
installStatePath: .yarn/install-state.gz

# Checksum behavior
enableImmutableInstalls: true

# Plugin settings
pluginsChecksum: null